### ISSUE TITLE
Improve messaging for connection types

### ISSUE THREAD

**Issue by dillfrescott** [jeremyckahn/chitchatter#124]
Hey Jeremy! Just checking in!

But mostly to ask, what does it mean when it says partial network connection and the dot is in yellow?

I can still do voice calls correct?

**Comment by jeremyckahn** [comment]
Hi @dillfrescott! It's good to hear from you. 🙂

> what does it mean when it says partial network connection and the dot is in yellow?

"Partial network connection" means that Chitchatter is able to connect to a WebTorrent server, but not a TURN relay server. This means that you'll only be able to connect with peers that don't require a TURN relay server connection (such two laptops connected via a home network connection). Notably, mobile peer connections may not work.

Based on what I'm seeing, Chitchatter is only able to achieve a partial network connection right now. This seems to be due to Open Relay having shut down its anonymous free service, as I predicted in #112. This will unfortunately remain the case until Chitchatter receives TURN server resources or financial support to purchase them.

> I can still do voice calls correct?

Yep, all Chitchatter functionality is available once you're connected to peers.

-------------------------------

The fact that this question needed to be asked implies that this part of the UX is unclear. I'm going to update this issue's title and add some better messaging around part of the app's UI so it's clearer for users.

**Comment by jeremyckahn** [comment]
I've added a tooltip for the network connection indicator that should hopefully make this behavior clearer. Thanks for raising this @dillfrescott!

**Comment by dillfrescott** [comment]
Thank you so much! Also thanks for the info!
