### ISSUE TITLE
Yunohost chitchatter

### ISSUE THREAD

**Issue by ralphshinevar** [jeremyckahn/chitchatter#153]
How can I get chitchatter to use the Coturn server that runs on my Yunohost server?

**Comment by jeremyckahn** [comment]
Hi @ralphshinevar, you'll need to modify your `rtcConfig` at `src/config/rtcConfig.ts` according to your Coturn server's configuration. Here's the default config for https://chitchatter.im/: https://github.com/jeremyckahn/chitchatter/blob/6529a0b4a7f7f00900a846055ef69ad86fffc254/src/config/rtcConfig.ts#L5-L32

Let me know if this doesn't work for you.

**Comment by ralphshinevar** [comment]
Hello Jeremy,  I added this to my src/config/rtcConfig.ts file with the coturn server credentials:

iceServers: [
    {
      urls: 'stun:shinevar.nohost.me;5349',
    },
    {
      urls: 'turn:shinevar.nohost.me;5349',
      username: 'turnserver',
      credential: 'pZUW6JS5rZFp2FdT72icDupU2Bkfp0',
    },
    {
      urls: 'turn:openrelay.metered.ca:443',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:openrelay.metered.ca:443?transport=tcp',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
  ],
}

Trickle Ice looks good:

Time	Type	Foundation	Protocol	Address	Port	Priority	URL (if present)	relayProtocol (if present)
0.002	host	583172148	udp	192.168.4.160	52318	126 | 32542 | 255		
0.007	srflx	599978514	udp	23.84.35.224	52318	100 | 32542 | 255	stun:turn.shinevar.nohost.me:5349	
0.131	host	1544381100	tcp	192.168.4.160	9	90 | 32542 | 255		
0.131	Done

Asking friends to come into my room.

**Comment by ralphshinevar** [comment]
So far no one is having any success getting to my room.

**Comment by ralphshinevar** [comment]
Hi Jeremy,  

I changed the ";" to ":" .   At the iceserver site, the stun works, but the turn server get a 401 error.  I am using the username/password given from Yunohost.  

The server turn:turn.shinevar.nohost.me:5349?transport=udp returned an error with code=401:
Unauthorized

Should this port be opened only TCP?

**Comment by jeremyckahn** [comment]
That question is a little out of my depth, so I'm afraid I can't help much there. It seems like there isn't a problem with Chitchatter itself, but rather the configuration of your TURN server (or perhaps the `rtcConfig` you have set up for your Chitchatter instance, which is just a [standard `RTCPeerConnection` configuration object](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#configuration)). I recommend opening an issue at the YunoHost fork's repo to see if they can help you: https://github.com/YunoHost-Apps/chitchatter_ynh

Good luck!

Additionally, I recommend updating your comment above to remove the server `credential`, since this is a public thread.
