### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by Audiosutras** [jeremyckahn/chitchatter#223]
It would be cool if we could integrate chitchatter with discord and other chat platforms such as slack.

For example in discord we could create the chitchatter bot that gives users the ability to generate public and private rooms along with links to the users in the discord server that are invited to that room.

**Comment by jeremyckahn** [comment]
@Audiosutras interesting idea! What you're describing seems like something that could be achieved in a way that is completely external to Chitchatter, since all that would be needed is a room name embedded in a Chitchatter URL. This isn't something that needs to be done from within Chitchatter. For instance, I can just type out https://chitchatter.im/public/github-issue-223 right here in GitHub, and opening the link would automatically create the room.

Is there some deeper level of Discord/Slack integration you're envisioning?

**Comment by Audiosutras** [comment]
Haha Nope that's it. I'll let you know about my progress on the bot @jeremyckahn

**Comment by jeremyckahn** [comment]
Sounds good! @Audiosutras I'll close this for now but feel free to comment if there's more to add here.
