### ISSUE TITLE
connection drop

### ISSUE THREAD

**Issue by i0day** [jeremyckahn/chitchatter#364]
Connection is either too slow or keep dropping after 20 seconds. It keeps search for peers forever not usable

**Comment by jeremyckahn** [comment]
It seems to be working well for me. It's possible that this is due to some transient network issues and will self-resolve in time. There may also be an issue that's specific to your network environment. In any case, I don't control the infrastructure that Chitchatter runs on so there's nothing that can be done on my end to address this.

**Comment by i0day** [comment]
Is it because of turn server? I am not sure if the nature of p2p and decentralized serveless cause it not as fast and reliable as the one with server? The connection takes more than 2 minutes to discover the peers in Local network and keeps dropping connection. I tried spectrum home internet and T-Mobile as well. I am not sure if it is the isp problem.

**Comment by jeremyckahn** [comment]
It's hard to say exactly. I don't have these issues, and I don't have a way of diagnosing what you're experiencing. What I can tell you is that Chitchatter currently uses https://www.expressturn.com/ (free tier) as its TURN server (which is needed to enable P2P connections under some network conditions), and its performance may not be the best (especially for some geographical locations). #112 is an open request for a better TURN resource from the community, as I am unable to provide it myself.

Sorry to hear this isn't working well for you. Hopefully somebody is able to come forward to provide a better server for the project!
