### ISSUE TITLE
File sharing is broken on Android

### ISSUE THREAD

**Issue by jeremyckahn** [jeremyckahn/chitchatter#82]
> file sharing doesn't seem to work from/to my android device. I tested it on 4 different browsers (Chrome, Brave, Duckduckgo, Firefox).

_Originally posted by @butera-simone in https://github.com/jeremyckahn/chitchatter/issues/72#issuecomment-1356894667_

**Comment by jeremyckahn** [comment]
I haven't been able to debug this yet. I've noticed that https://github.com/webtorrent/instant.io also does not work on Android, which is another WebTorrent-based file transfer web app. This further suggests that the root of the issue is in WebTorrent.

**Comment by butera-simone** [comment]
Interesting. I now checked instant.io from my devices (Linux desktop and Android) and yes, it seems to be broken on Android. Before finding ChitChatter and Trystero, I've tried a lot of P2P projects, and most of them gave me problems; but then again, most of them had open issues in which was stated that the problem was Heroku shutting down the hosting service they were using for their relay, or some other hosting problem. But probably a few of them were based on WebTorrent too.

WebTorrent is not a Trystero dependency, right? I just built a small file sending test with Trystero now and it works for my phone, at what size do you start needing WebTorrent in your opinion?

**Comment by jeremyckahn** [comment]
> WebTorrent is not a Trystero dependency, right?

Not in terms of code dependencies, no. However, Chitchatter uses the [WebTorrent connection strategy](https://github.com/dmotz/trystero#strategy-comparison), which means it uses WebTorrent servers to initiate peer connections.

> I just built a small file sending test with Trystero now and it works for my phone, at what size do you start needing WebTorrent in your opinion?

Trystero works great for transferring files so long as the files' data can reasonably fit within the memory space available to the web app. The sender would need to first load the file contents into memory before transferring it, and the receiver would need to also hold the entire file in memory before persisting it to disk. So, file sizes would be limited to the runtime memory available to peers. Chitchatter should support arbitrary file sizes (potentially many gigabytes), and WebTorrent seems to be the best client-side solution for doing that (at least when using https://github.com/SocketDev/idb-chunk-store to hold transferred chunks on disk rather than in memory, as Chitchatter does).

I will report this issue to the instant.io project. It's maintained by the developers of WebTorrent, so that would probably be the best way to raise visibility of this issue.

**Comment by jeremyckahn** [comment]
This appears to be fixed by https://github.com/jeremyckahn/chitchatter/commit/99a9ab783815e3bddeebd0de8ad74d010e5162b1.
